[package]
name = "omniregress"
version = "4.0.0"
edition = "2021"

[lib]
name = "_omniregress" # Name of the compiled library for Python import
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }


