from typing import Optional, List

class LinearRegression:
    def __init__(self) -> None: ...
    def fit(self, x: 'numpy.ndarray[numpy.float64]', y: 'numpy.ndarray[numpy.float64]') -> None: ...
    def predict(self, x: 'numpy.ndarray[numpy.float64]') -> 'numpy.ndarray[numpy.float64]': ...
    def score(self, x: 'numpy.ndarray[numpy.float64]', y: 'numpy.ndarray[numpy.float64]') -> float: ...
    @property
    def coefficients(self) -> Optional[List[float]]: ...
    @property
    def intercept(self) -> Optional[float]: ...

from .polynomial_regression import PolynomialRegression

__version__ = "2.0.0"
__all__ = ['LinearRegression', 'PolynomialRegression']