# .github/workflows/release.yml

name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-to-pypi:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest

    # --- ADD THIS BLOCK ---
    # This explicitly grants the GITHUB_TOKEN the permissions it needs.
    # The action needs to read repository contents to function correctly.
    permissions:
      contents: read
    # ----------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and publish wheels using maturin
        uses: PyO3/maturin-action@v1
        with:
          command: publish
          token: ${{ secrets.PYPI_API_TOKEN }}