# .github/workflows/release.yml

name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and publish wheels
        uses: PyO3/maturin-action@v1
        with:
          command: publish
          # Use the secret token for PyPI authentication
          tokens: ${{ secrets.PYPI_API_TOKEN }}