# .github/workflows/release.yml

name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wheels with maturin
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --strip
          manylinux: auto

      - name: Publish to PyPI with Twine
        uses: pypa/gh-action-pypi-publish@release
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: target/wheels/